from fastapi import APIRouter
from datetime import datetime, date, timedelta
from app.core.dependencies import DbSession, CurrentEmployee
from app.models.leave import LeaveRequest, LeaveRequestStatus
from app.models.employee import Employee, RoleEnum
from typing import Optional

router = APIRouter(prefix="/api/dashboard", tags=["Dashboard"])

# Curated list of Gurudev Sri Sri Ravishankar quotes (rotated by day of year)
GURUDEV_QUOTES = [
    "Love is not an emotion. It is your very existence.",
    "Stress is nothing but the inability to handle the present moment.",
    "When you are full of joy, you want to share. That is service.",
    "Gratitude is the mother of all virtues.",
    "Life is a mixture of sunshine and rain, joy and pain. Accept them all.",
    "Wisdom is knowing that you are a part of the whole, not apart from it.",
    "Meditation is the journey from sound to silence, from movement to stillness.",
    "Your breath is your best friend. Return to it in all your troubles.",
    "Serve, love, give, and smile. That is the path to happiness.",
    "The mind that is always wanting is distracted. The mind that is content is centred.",
    "Every moment is unique, unknown, and completely fresh.",
    "When you are happy, you want to spread it around. That happiness is service.",
    "Knowledge without devotion is dry. Devotion without knowledge is blind.",
    "Be like a flower — face the sun and spread your fragrance.",
    "The purpose of life is to be useful, to be honourable, to be compassionate.",
    "Peace is not something you wish for. It is something you make, something you do, something you are.",
    "Your smile is not just a curve — it sets everything straight.",
    "The quality of your consciousness is more important than your circumstances.",
    "True love is not based on conditions. It simply exists.",
    "Every obstacle is an opportunity for growth.",
    "When you help others, you are helping yourself. We are all one.",
    "Silence speaks louder than words. Listen to it.",
    "The greatest wealth is health of body, mind and spirit.",
    "Service to others is the rent you pay for your room here on earth.",
    "Begin each day with gratitude and end it with grace.",
    "Your mind is like a mirror — it reflects what you bring to it.",
    "Enthusiasm is the elixir of life. Keep it alive.",
    "A smile is the light in your window that tells others you are home.",
    "Life is short. Make it sweet and meaningful.",
    "Be the change you wish to see in the world.",
    "In giving, we receive. In serving, we grow.",
    "The secret of happiness is not in doing what one likes, but in liking what one does.",
    "Be kind. Everyone you meet is fighting a hard battle.",
    "The heart that gives, gathers.",
    "One kind word can change someone's entire day.",
    "You are a wave of the ocean. Know your vastness.",
    "Awaken the spirit within you — it is your greatest strength.",
    "Calm mind brings inner strength and self-confidence.",
    "Love is not something you search for. It is something you become.",
    "The essence of love is to accept everyone as they are.",
    "When love flows, life blossoms in ways you never imagined.",
    "Love is the fragrance that the heart naturally radiates.",
    "In the garden of humanity, love is the only seed worth planting.",
    "When you serve, you discover the divinity within yourself.",
    "Selfless service cleanses the mind and purifies the heart.",
    "Service is the rent we pay for the privilege of living.",
    "The highest form of service is done without any sense of doership.",
    "When you serve with a smile, you make the world a better place.",
    "Meditation is the art of doing nothing and yet accomplishing everything.",
    "In meditation, the soul finds rest and the mind finds peace.",
    "A few minutes of meditation can transform your entire day.",
    "Meditation is not about stopping thoughts. It is about witnessing them.",
    "When you sit in silence, the universe reveals its secrets to you.",
    "Every breath is a reminder that you are alive and blessed.",
    "The breath is the river of life flowing through you constantly.",
    "When you breathe consciously, you awaken the healing power within.",
    "Your breath is the connection between the body and the soul.",
    "Breathing with awareness is the simplest form of meditation.",
    "Joy is not a destination. It is the way you travel.",
    "When you are full of joy, life becomes a celebration.",
    "Joy is the natural state of the soul when it is free.",
    "Share your joy and watch it multiply a thousandfold.",
    "True joy comes from within, not from external circumstances.",
    "Peace is the highest goal of human life.",
    "When you are at peace within, you create peace without.",
    "Inner peace is the foundation of a meaningful life.",
    "Peace does not mean the absence of conflict. It means the presence of love.",
    "The world needs peace, and it begins with you.",
    "Wisdom is the eye that sees beyond the appearance of things.",
    "True wisdom is knowing what you do not know.",
    "Wisdom is the daughter of patience and the mother of peace.",
    "When wisdom dawns, ignorance dissolves like darkness before light.",
    "The wise person speaks less and listens more.",
    "Nature teaches us the art of effortless living.",
    "In the stillness of nature, you hear the voice of the divine.",
    "Every leaf of the tree becomes a page of the book once the tree is read.",
    "Nature is the greatest healer. Spend time among trees and flowers.",
    "When you are in harmony with nature, you are in harmony with yourself.",
    "Gratitude opens the door to abundance and joy.",
    "A grateful heart is a magnet for miracles.",
    "When you are grateful for what you have, life gives you more to be grateful for.",
    "Gratitude turns ordinary days into blessings.",
    "Thankfulness is the beginning of all virtues.",
    "Compassion is the root of all religion and spirituality.",
    "When you feel the pain of another, you are truly alive.",
    "Compassion is the bridge between hearts separated by fear.",
    "Let compassion guide your actions, and you will never go wrong.",
    "A compassionate heart is a healing heart.",
    "True strength is the ability to be soft and strong at the same time.",
    "The strength of the soul is greater than any circumstance.",
    "When you are rooted in love, you become unshakable.",
    "Strength is not about muscles. It is about the spirit.",
    "The greatest strength is the power to forgive.",
    "In silence, the soul speaks its deepest truths.",
    "Silence is the music of the spirit.",
    "The quieter you become, the more you can hear.",
    "Silence is not the absence of sound. It is the presence of awareness.",
    "When words fail, silence speaks volumes.",
    "Simplicity is the shortest distance to authenticity.",
    "Live simply so that others may simply live.",
    "In simplicity, you find the profound beauty of existence.",
    "The simple life is the most fulfilling life.",
    "Simplicity is not about having less. It is about making room for more.",
    "Devotion is the sweet nectar that the soul longs for.",
    "When the heart is devoted, every action becomes sacred.",
    "Devotion melts the hardness of the heart.",
    "True devotion is living every moment with love and awareness.",
    "The devotion of the heart is greater than the knowledge of the mind.",
    "Humanity is the highest religion.",
    "When you serve humanity, you serve the divine.",
    "We are all threads in the beautiful tapestry of humanity.",
    "The welfare of humanity is the ultimate purpose of life.",
    "In every human being, there is a spark of the divine waiting to be acknowledged.",
    "Self-awareness is the beginning of all transformation.",
    "When you know yourself, you know the universe.",
    "The unexamined life is not worth living.",
    "Self-awareness is the greatest gift you can give yourself.",
    "Knowing yourself is the beginning of wisdom.",
    "Inner peace is the new success.",
    "When the mind is calm, the soul is at rest.",
    "Nothing can disturb your inner peace unless you allow it.",
    "Inner peace is the treasure that no one can steal from you.",
    "The peace that you seek outside is already within you.",
    "Happiness is not a position. It is a disposition.",
    "True happiness comes from making others happy.",
    "Happiness is the absence of the comparison of the mind.",
    "When you stop seeking happiness, you find it.",
    "Happiness is your birthright. Claim it.",
    "Kindness is the language the whole world understands.",
    "A single act of kindness can change the course of someones life.",
    "Kindness is the strength of the strong.",
    "Be kind to yourself first, and kindness to others will follow naturally.",
    "Kindness is the greatest wisdom.",
    "Courage is not the absence of fear. It is acting in spite of it.",
    "It takes courage to be vulnerable and real.",
    "Courage is the willingness to be imperfect.",
    "The brave person is not the one who does not feel afraid, but the one who conquers that fear.",
    "Courage is the foundation of all great achievements.",
    "Faith is taking the first step even when you do not see the whole staircase.",
    "When faith is strong, mountains crumble.",
    "Faith is the bird that feels the light and sings when the dawn is still dark.",
    "Let faith be bigger than your fears.",
    "With faith, all things are possible.",
    "Surrender is not giving up. It is giving over to a higher intelligence.",
    "When you surrender, you discover a power greater than yourself.",
    "The moment you surrender, grace enters your life.",
    "Surrender the need to control and watch miracles unfold.",
    "True surrender is trusting the divine plan completely.",
    "Mindfulness is paying attention on purpose, in the present moment.",
    "When you are mindful, every moment becomes sacred.",
    "Mindfulness is the art of being fully present in your life.",
    "A mindful life is a life well lived.",
    "Mindfulness brings clarity, calmness, and compassion.",
    "We are all one family under the canopy of the divine.",
    "Unity in diversity is the hallmark of creation.",
    "When you see unity in all, you have found the truth.",
    "The feeling of oneness is the highest meditation.",
    "Behind all the differences, there is an underlying unity.",
    "Generosity is not about how much you give, but how much love you put into giving.",
    "The generous person is always rich in spirit.",
    "Give generously and receive abundantly.",
    "True generosity is giving without expecting anything in return.",
    "A generous heart is a happy heart.",
    "Truth is one. The wise call it by many names.",
    "Truth is the backbone of a fulfilling life.",
    "When you live in truth, you live in freedom.",
    "The truth will set you free, but first it may disturb you.",
    "Truth is simple, yet the mind complicates it.",
    "Non-violence is the supreme religion.",
    "When you practice non-violence, you create harmony around you.",
    "Ahimsa paramo dharma. Non-violence is the highest duty.",
    "Non-violence is not just a principle. It is a way of life.",
    "The power of non-violence is greater than the power of weapons.",
    "The world is a mirror of your inner state.",
    "When you change yourself, the world changes around you.",
    "Every challenge carries within it the seed of equivalent grace.",
    "You are the author of your own story. Write it with love.",
    "The divine plays in every atom of this creation.",
    "When the student is ready, the teacher appears.",
    "Let your life be an expression of love and service.",
    "The greatest prayer is a life lived with awareness.",
    "When you are full of love, fear has no place.",
    "Each moment is a new canvas. Paint it with kindness.",
    "The soul never ages. It only grows wiser.",
    "When you smile at life, life smiles back at you.",
    "The present moment is the only moment available to us.",
    "A relaxed mind is a creative and powerful mind.",
    "When you let go of expectations, you welcome miracles.",
    "The quality of your life depends on the quality of your attention.",
    "Divinity dwells in every heart, waiting to be recognized.",
    "True healing begins when you start loving yourself.",
    "When the heart is pure, thoughts become powerful.",
    "The purpose of meditation is to befriend yourself.",
    "Let kindness be your compass in every situation.",
    "When you breathe with awareness, you connect with the cosmos.",
    "Love transforms everything it touches.",
    "In kindness, you find the true wealth of life.",
    "The soul rejoices in service and celebration.",
    "Every breath is an opportunity to start anew.",
    "When you are centered, the world centers around you.",
    "The greatest discovery is the discovery of the self.",
    "Let go of anger. It poisons only you.",
    "Joy is the divine glow of the soul.",
    "When you serve, you earn the blessings of the divine.",
    "Peace is the reward of a disciplined mind.",
    "Every sunset reminds us that endings can be beautiful too.",
    "The fragrance of a good life spreads far and wide.",
    "When you are present, you are powerful.",
    "True success is measured by the joy you create.",
    "Let your heart be the temple where love resides.",
    "The mind that serves is the mind that shines.",
    "When you practice gratitude, life becomes a dance.",
    "The soul finds home in the lap of nature.",
    "Be patient with yourself. Growth takes time.",
    "When you breathe with love, every cell celebrates.",
    "The greatest gift of the present moment is peace.",
    "Let wisdom be your guide and love be your path.",
    "When you are at peace, you attract peace.",
    "The breath is the anchor of the wandering mind.",
    "True freedom is freedom from negative thoughts.",
    "When you listen with your heart, you hear the truth.",
    "The greatest healer is the love within you.",
    "Every flower is a reminder of the beauty of life.",
    "When you are rooted in gratitude, nothing can shake you.",
    "The journey inward is the greatest adventure of all.",
    "Let your actions speak louder than your words.",
    "When you are content, the whole world is yours.",
    "True intelligence is the ability to see the divine in all.",
    "The soul sparkles when it serves without motive.",
    "When you are in the present, the past has no power.",
    "Nature never rushes, yet everything blossoms in time.",
    "The light within you is brighter than any darkness around you.",
    "When you breathe deeply, you breathe in the infinite.",
    "True mastery is the mastery of the self.",
    "Let compassion be the foundation of every relationship.",
    "When you let love lead, you never lose your way.",
    "The mind becomes what it repeatedly thinks.",
    "True silence is the rest of the overworked mind.",
    "Every moment of awareness is a moment of freedom.",
    "When you share your joy, it grows endlessly.",
    "The greatest art is the art of living well.",
    "Let your life be a testimony of love and service.",
    "When you are at ease, the world is at ease with you.",
    "The soul dances when the heart is light.",
    "True power is the power to remain calm under pressure.",
    "When you breathe with awareness, stress dissolves.",
    "The greatest offering you can make is a sincere smile.",
    "Let your thoughts be pure, and your life will be beautiful.",
    "When you are grateful, you are already abundant.",
    "The heart that serves is the heart that blooms.",
    "True beauty is the radiance of a loving soul.",
    "When you meditate, you polish the mirror of the soul.",
    "The greatest victory is the victory over the self.",
    "Let love be the language you speak every day.",
    "When you give with joy, the universe conspires to give back.",
    "The breath is the thread that stitches the soul to the body.",
    "True happiness is found in the simplicity of being.",
    "When you are kind, you touch the heart of God.",
    "The soul sings when the mind is at peace.",
    "True greatness lies in humble service.",
    "When you let go, the divine takes over.",
    "The greatest wisdom is to know that wisdom is not enough without love.",
    "Let your heart overflow with gratitude and kindness.",
    "When you are calm, you can hear the whispers of the soul.",
    "The breath is the sacred melody of existence.",
    "True love sees the divine in every being.",
    "When you are at home in your heart, you are at home everywhere.",
    "The soul is nourished by moments of stillness.",
    "True contentment is the greatest wealth.",
    "When you breathe with presence, you discover the infinite.",
    "The greatest teacher is life itself.",
    "Let your life be a song of devotion.",
    "When you serve with love, the divine serves through you.",
    "The mind at peace is the mind at its most powerful.",
    "True forgiveness is the gift you give yourself.",
    "When you are rooted in awareness, you are rooted in truth.",
    "The soul rejoices in the beauty of the present moment.",
    "True giving is giving without counting the cost.",
    "When you breathe with gratitude, life becomes a prayer.",
    "The greatest comfort is the comfort of the soul.",
    "Let your words be gentle and your actions be kind.",
    "When you are free from comparison, you are truly free.",
    "The soul finds its home in the stillness of the heart.",
    "True listening is the greatest act of love.",
    "When you practice patience, you practice love.",
    "The greatest richness is the richness of the spirit.",
    "Let your presence be a blessing to everyone you meet.",
    "When you are centered in awareness, you are centered in God.",
    "The soul is nourished by acts of kindness.",
    "True understanding comes from the heart, not the mind.",
    "When you breathe with love, the whole world breathes with you.",
    "The greatest gift you can offer is your undivided attention.",
    "Let your life be an offering of love and light.",
    "When you are at peace within, you become a beacon of peace.",
    "The soul finds its true expression in service and devotion.",
    "True courage is the courage to be compassionate.",
    "When you meditate, you connect with the universal consciousness.",
    "The greatest strength is the strength of a loving heart.",
    "Let your inner light illuminate the path for others.",
    "When you are full of gratitude, life overflows with blessings.",
    "The soul dances in the rain of divine grace.",
    "True awareness is the key to inner transformation.",
    "When you breathe with devotion, every breath becomes sacred.",
    "The greatest joy is the joy of giving.",
    "Let kindness ripple through every corner of your being.",
    "When you surrender to the present, you discover eternity.",
    "The soul is the eternal witness of all experience.",
    "True simplicity is the hallmark of a soul at peace.",
    "When you practice non-violence, you heal the world.",
    "The greatest celebration is the celebration of being alive.",
    "Let love permeate every cell of your body.",
    "When you are rooted in compassion, you become a tree of shelter for all.",
    "The soul shines brightest in the light of selfless service.",
    "True wisdom is the wisdom of the heart.",
    "When you breathe with awareness, you awaken the dormant potential within.",
    "The greatest blessing is the blessing of inner peace.",
    "Let your heart be the altar of love and gratitude.",
    "When you are at ease with uncertainty, you embrace life fully.",
    "The soul finds its purpose in serving the greater good.",
    "True generosity is the generosity of the spirit.",
    "When you meditate with devotion, you touch the feet of the divine.",
    "The greatest reward of service is the joy it brings.",
    "Let your thoughts be seeds of peace and love.",
    "When you breathe with joy, you bless the world around you.",
    "The soul finds its rest in the embrace of silence.",
    "True humility is the gateway to divine grace.",
    "When you live with integrity, your life becomes a prayer.",
    "The greatest harmony is the harmony of body, mind, and soul.",
    "Let your smile be a gift to the world.",
    "When you are grounded in love, you become unshakable.",
    "The soul rejoices when the mind is still.",
    "True patience is the companion of wisdom.",
    "When you breathe with awareness, you align with the cosmic rhythm.",
    "The greatest treasure is the treasure of a pure heart.",
    "Let your presence bring peace and comfort to others.",
    "When you let go of resistance, life flows effortlessly.",
    "The soul is eternal, infinite, and ever-new.",
    "True faith is the trust in the goodness of life.",
    "When you practice mindfulness, every action becomes sacred.",
    "The greatest discovery is the discovery of your own inner divinity.",
    "Let your life be a reflection of the love you carry within.",
    "When you are at peace with yourself, you are at peace with the world.",
    "The soul finds its freedom in the acceptance of what is.",
    "True surrender is the ultimate act of courage.",
    "When you breathe with love, you heal the wounds of the past.",
    "The greatest light is the light of awareness.",
    "Let your heart be open, your mind be clear, and your soul be free.",
    "When you serve without expectation, you discover the joy of selfless love.",
    "The soul is always fresh, new, and full of wonder.",
    "True stillness is the doorway to infinite creativity.",
    "When you practice gratitude, you transform challenges into opportunities.",
    "The greatest peace is the peace that comes from within.",
    "Let your actions be guided by love, your words be guided by truth.",
    "When you breathe with devotion, the divine breathes through you.",
    "The soul dances in the light of infinite love.",
    "True awareness is the recognition that you are not the body or the mind.",
    "When you live with love, you live with the infinite.",
    "The greatest service is to awaken the divine in others.",
    "Let every breath be a reminder of the miracle of life.",
    "When you are grounded in truth, you are grounded in eternity.",
    "The soul finds its home in the temple of the heart.",
    "True devotion is not in rituals but in the attitude of love.",
    "When you breathe with joy, you radiate joy to the world.",
    "The greatest happiness is the happiness of others.",
    "Let your inner peace be your greatest strength."
]


@router.get("/events")
def get_dashboard_events(db: DbSession, current_user: CurrentEmployee):
    """Return today's events, upcoming leaves, and a daily Gurudev quote for the dashboard."""
    today = date.today()
    day_of_year = today.timetuple().tm_yday
    quote = GURUDEV_QUOTES[day_of_year % len(GURUDEV_QUOTES)]

    events = []
    user_upcoming_leave = None
    is_birthday = False

    # ── Birthday check for current user ──
    if current_user.date_of_birth:
        dob = current_user.date_of_birth
        if dob.month == today.month and dob.day == today.day:
            is_birthday = True

    # ── Upcoming leave for current user (next 7 days) ──
    next_week = today + timedelta(days=7)
    upcoming = db.query(LeaveRequest).filter(
        LeaveRequest.employee_id == current_user.id,
        LeaveRequest.status == LeaveRequestStatus.APPROVED,
        LeaveRequest.start_date >= today,
        LeaveRequest.start_date <= next_week
    ).first()
    if upcoming:
        user_upcoming_leave = {
            "start_date": str(upcoming.start_date),
            "end_date": str(upcoming.end_date),
            "total_days": upcoming.total_days,
            "is_half_day": upcoming.is_half_day,
            "half_day_period": upcoming.half_day_period,
        }

    # ── For HR / Admin / SuperAdmin: dept-wide events today ──
    if current_user.role in [RoleEnum.HR, RoleEnum.ADMIN, RoleEnum.SUPER_ADMIN, RoleEnum.HOD]:
        # Leaves starting today
        query = db.query(LeaveRequest).filter(
            LeaveRequest.status == LeaveRequestStatus.APPROVED,
            LeaveRequest.start_date == today,
            LeaveRequest.total_days >= 3
        )
        if current_user.role == RoleEnum.HOD:
            dept_employee_ids = [
                s.id for s in db.query(Employee).filter(Employee.department_id == current_user.department_id).all()
            ]
            query = query.filter(LeaveRequest.employee_id.in_(dept_employee_ids))

        long_leaves_today = query.all()
        for lr in long_leaves_today:
            employee = db.query(Employee).filter(Employee.id == lr.employee_id).first()
            if employee:
                events.append({
                    "type": "LONG_LEAVE_START",
                    "message": f"{employee.first_name} {employee.last_name}'s {lr.total_days}-day leave starts today.",
                    "employee_name": f"{employee.first_name} {employee.last_name}",
                })

        # Birthdays today (all employees for HR/Admin, dept only for HOD)
        employee_query = db.query(Employee).filter(
            Employee.date_of_birth != None
        )
        if current_user.role == RoleEnum.HOD:
            employee_query = employee_query.filter(Employee.department_id == current_user.department_id)

        all_employees = employee_query.all()
        for s in all_employees:
            if s.date_of_birth and s.date_of_birth.month == today.month and s.date_of_birth.day == today.day:
                if s.id != current_user.id:
                    events.append({
                        "type": "BIRTHDAY",
                        "message": f"Today is {s.first_name} {s.last_name}'s birthday! 🎂",
                        "employee_name": f"{s.first_name} {s.last_name}",
                    })

    return {
        "quote": quote,
        "is_birthday": is_birthday,
        "events": events,
        "upcoming_leave": user_upcoming_leave,
        "today": str(today),
        "user_first_name": current_user.first_name,
    }
